const overlayNames={AliveStatus:'Alive Status',ElimBroadcast:'Elimination Broadcast',TopAliveStatus:'Top Alive Status',TeamPreview:'Team Preview',ZoneTimer:'Zone Timer',FirstPick:'First Pick',MatchResult:'Match Result',OverallResult:'Overall Result',WWCD:'WWCD Team Stats',PrizePool:'Prize Pool',MVP:'MVP',Domination:'Team Domination'};
let defaultsByOverlay={};
const list=document.getElementById('list'),search=document.getElementById('search');
function safeDate(value){try{return new Date(value).toLocaleString()}catch(error){return ''}}
function render(){const term=search.value.trim().toLowerCase(),items=window.EventPresets.list().filter(item=>item.name.toLowerCase().includes(term));list.replaceChildren();if(!items.length){const empty=document.createElement('p');empty.className='note';empty.textContent='No event presets yet. Create one to capture the current production configuration.';list.append(empty);return}items.forEach(item=>{const row=document.createElement('article');row.className='preset-item';const details=document.createElement('div');const title=document.createElement('strong');title.textContent=item.name;const meta=document.createElement('small');meta.textContent='Updated '+safeDate(item.updatedAt)+' · '+Object.keys(item.overlays||{}).length+' overlays';details.append(title,meta);const actions=document.createElement('div');actions.className='preset-actions';[['EDIT',()=>location.href='preset-editor.html?id='+encodeURIComponent(item.id)],['APPLY',()=>apply(item)],['DUPLICATE',()=>duplicate(item)],['DELETE',()=>remove(item)]].forEach(([label,handler])=>{const button=document.createElement('button');button.className='btn'+(label==='APPLY'?' primary':label==='DELETE'?' danger':'');button.textContent=label;button.onclick=handler;actions.append(button)});row.append(details,actions);list.append(row)})}
function create(){const name=prompt('Event preset name');if(name===null)return;try{const preset=window.EventPresets.create(name,defaultsByOverlay);location.href='preset-editor.html?id='+encodeURIComponent(preset.id)}catch(error){alert(error.message)}}
function duplicate(item){const name=prompt('Name for the copied preset',item.name+' Copy');if(name===null)return;try{window.EventPresets.duplicate(item.id,name);render()}catch(error){alert(error.message)}}
function remove(item){if(confirm('Delete the event preset "'+item.name+'"? This does not change the currently active production settings.')){window.EventPresets.remove(item.id);render()}}
async function apply(item){if(!confirm('Apply "'+item.name+'" to all production overlays? This overwrites the currently active overlay settings only.'))return;const buttons=[...document.querySelectorAll('button')];buttons.forEach(button=>button.disabled=true);try{const result=await window.EventPresets.apply(item.id);alert(result.cloudErrors.length?'Preset applied locally. Cloud sync failed for: '+result.cloudErrors.join(', '):'Preset applied to all production overlays.')}catch(error){alert('Could not apply preset: '+error.message)}finally{buttons.forEach(button=>button.disabled=false)}}
fetch('overlay-config.json').then(response=>response.json()).then(config=>{Object.entries(overlayNames).forEach(([overlay])=>{defaultsByOverlay[overlay]=Object.fromEntries((config[overlay]||[]).map(item=>[item.var,item.default]))});render()}).catch(error=>{list.textContent='Could not load production settings: '+error.message});
document.getElementById('create').onclick=create;search.oninput=render;
